
service: api-dr-get-debts
app: app-debts-register-tp
org: yeison

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  get-token:
    handler: handler/handler.get
    events:
      - httpApi: '*'
