
service: api-dr-get-debts
app: app-debts-register-tp
org: yeison

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${sls:stage}-debts
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  get-debts:
    handler: handler.handler
    events:
      - httpApi:
          path: /debts/{id}
          method: get
  